activation: silu
aggregation_method: sum
anchors_context: true
attention: false
batch_size: 8
center_of_mass: anchors
context_node_nf: 3
data_augmentation: false
data_path: data/data
diffusion_loss_type: l2
diffusion_noise_precision: 1.0e-05
diffusion_noise_schedule: polynomial_2
diffusion_steps: 500
hidden_nf: 128
in_node_nf: 12
include_charges: false
inpainting: false
inv_sublayers: 2
log_iterations: null
lr: 0.0002
model: egnn_dynamics
n_dims: 3
n_layers: 6
n_stability_samples: 5
norm_constant: 1.0e-06
normalization: batch_norm
normalization_factor: 100
normalize_factors:
- 1
- 4
- 10
samples_dir: logs/samples/ADOptDiff_chensn_ADOPTDIFF_bs8_date07-07_time15-34-44.456667
sin_embedding: false
tanh: false
test_epochs: 20
torch_device: cuda:0
train_data_prefix: bingdingnet_train.full
val_data_prefix: bingdingnet_test.full
